### ISSUE TITLE
position of MOpt splice

### ISSUE THREAD

**Issue by akasong** [AFLplusplus/AFLplusplus#1399]
I keep looking at the code associated with #1394.

```
#define STAGE_RANDOMBYTE 12
#define STAGE_DELETEBYTE 13
#define STAGE_Clone75 14
#define STAGE_OverWrite75 15
#define STAGE_OverWriteExtra 16
#define STAGE_InsertExtra 17
#define STAGE_Splice 18
```

In AFLplusplus, STAGE_Splice was added from MOpt-AFL, but I think extra-stages should be placed at the very end because of the selection algorithm. so the STAGE_Splice should be placed before extra-stages(16,17). (and also related code modifications)
Am I missing something?

**Comment by vanhauser-thc** [comment]
I am not that deep into MOpt to be honest, and added this because we added the feature to normal havoc, hence I ported it into Mopt. Likely that I did not do that optimally as I am missing details how MOpt actually works. As it is not that effective (it is only 30% of the time better than normal havoc) I never looked deep into it.
If you tell me the splice stage should be moved, then I can do it. you can also send a PR and have your name in the commits :)

**Comment by vanhauser-thc** [comment]
@akasong will you send a PR? or is your proposed change not necessary?

**Comment by akasong** [comment]
I am not sure that the result of the whole fuzzer would be better. (not partial algorithm) 
So, after sufficient testing, I will send a PR when I am convinced.

**Comment by vanhauser-thc** [comment]
thank you!
