### ISSUE TITLE
Segmentation fault when build afl++ frida_mode for android 

### ISSUE THREAD

**Issue by icepng** [AFLplusplus/AFLplusplus#1520]
I try to build afl++ frida_mode for android but got the `Segmentation fault`

``` bash
➜  frida_mode git:(stable) env |grep CC
CC=/home/fuzz/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android22-clang
➜  frida_mode git:(stable) env |grep CXX
CXX=/home/fuzz/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android22-clang++

➜  frida_mode git:(stable) make ARCH=arm64
cd /home/fuzz/AFLplusplus/frida_mode/src/js/ && /home/fuzz/AFLplusplus/frida_mode/build/bin2c api_js /home/fuzz/AFLplusplus/frida_mode/src/js/api.js /home/fuzz/AFLplusplus/frida_mode/build/api.c
Segmentation fault (core dumped)
make: *** [GNUmakefile:349: /home/fuzz/AFLplusplus/frida_mode/build/api.c] Error 139
```

**Comment by vanhauser-thc** [comment]
@WorksButNotTested

**Comment by WorksButNotTested** [comment]
Thanks for the bug report. Looks like the issue is in this little tool. https://github.com/AFLplusplus/AFLplusplus/blob/stable/frida_mode/util/bin2c.c

It takes an input file and tries to generate a C source file from it which contains the input file represented as a byte array.

It runs on the host architecture rather than target if cross compiling, which should make things easier.

Are you able to run it in the debugger and try to narrow down the fault?

**Comment by WorksButNotTested** [comment]
/home/fuzz/AFLplusplus/frida_mode/build/bin2c api_js /home/fuzz/AFLplusplus/frida_mode/src/js/api.js /home/fuzz/AFLplusplus/frida_mode/build/api.c

It’s arguments are the name of the byte array to generate, the input file and the output source file to generate.

**Comment by WorksButNotTested** [comment]
> @WorksButNotTested

Thanks for the @.

**Comment by icepng** [comment]
I found the arch of `bin2c` is `aarch64` not `x86_64`.  It seems the tool is compiled using cross-compile tools.

```
➜  build git:(stable) file bin2c
bin2c: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, not stripped
```

**Comment by icepng** [comment]
> /home/fuzz/AFLplusplus/frida_mode/build/bin2c api_js /home/fuzz/AFLplusplus/frida_mode/src/js/api.js /home/fuzz/AFLplusplus/frida_mode/build/api.c
> 
> It’s arguments are the name of the byte array to generate, the input file and the output source file to generate.

Thanks for your reply, I think maybe I found the reason. In GNUmakefile, the `TARGET_CC` and the `HOST_CC` all set to `$CC`, which cause the `bin2c` is compiled to `aarch64`. I try to change all `HOST_CC` to `CC_HOST` like below, 
```
HOST_CC?=$(CC_HOST)
HOST_CXX?=$(CXX_HOST)
```

And set the ENV.
 ```
➜  frida_mode git:(stable) ✗ env |grep CC
CC_HOST=clang
CC=/home/fuzz/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
➜  frida_mode git:(stable) ✗ env |grep CXX
CXX_HOST=clang++
CXX=/home/fuzz/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
```
 
I use this to solve the problem of cross-compile

**Comment by WorksButNotTested** [comment]
The ?= should only take effect if no environment variable is set prior to make being called (it’s effectively a default). Both default to CC, since that’s what you want if you don’t cross compile. If you just set HOST_CC/CXX and TARGET_CC/CXX before you build it should take care of things. Hope that helps.
