### ISSUE TITLE
MOpt documentation is missing

### ISSUE THREAD

**Issue by neuschaefer** [AFLplusplus/AFLplusplus#1696]
afl-fuzz prints:

```
  -L minutes    - use MOpt(imize) mode and set the time limit for entering the
                  pacemaker mode (minutes of no new finds). 0 = immediately,
                  -1 = immediately and together with normal mutation.
                  See docs/README.MOpt.md
```

But, during the import of MOpt (commit 198946231c389acaea10bf047f70264a27617b02), docs/README.MOpt got lost somehow.

I guess some of the missing information could be pulled from the [MOpt git repo](https://github.com/puppet-meteor/MOpt-AFL).

**Comment by vanhauser-thc** [comment]
ah yes we removed that readme because it was not of much help. I just removed the link to it, thanks for pointing that out.
Mopt is a difficult thing for us. a) most of the time it is not as effective as the default mode and b) we are overhauling havoc mode very soon, but are not having the resources to update MOpt mode with the changes, leaving it in an partially outdated state.

**Comment by neuschaefer** [comment]
Thanks! Presenting consistent information was my main concern here.
