### ISSUE TITLE
About qemu_mode for avr system

### ISSUE THREAD

**Issue by Ray0124** [AFLplusplus/AFLplusplus#1704]
Hi , I want to ask that does the AFL++'s qemu_mode support avr-system(8bit atmel mcu)? or the other modes can do this?

**Comment by vanhauser-thc** [comment]
qemu_mode is qemu user mode, which means the targets need to be linux elf binaries you want to fuzz. if there is a linux for 8bit avr ;-) then it should work (with maybe a few changes to the source).
otherwise you need to use unicorn_mode or check out full system fuzzing with https://github.com/AFLplusplus/libafl

**Comment by Ray0124** [comment]
Ok, I got it. I will take some time for it. Thx for replying so quickly : )

**Comment by vanhauser-thc** [comment]
if you patch qemu to make it work, please send a PR to https://github.com/AFLplusplus/qemuafl
