### ISSUE TITLE
Ignore ranges of input file

### ISSUE THREAD

**Issue by ammonriley** [AFLplusplus/AFLplusplus#173]
Every few years, it seems that someone asks how to ignore part of a file for fuzzing.

Many of the test files I need to use to exercise certain portions of my library are very large, exceeding many MB, and some into the GB range.  They consist of small bits of metadata interspersed with opaque blobs of binary data.  Obviously, I want to fuzz the metadata, and ignore these opaque blobs (which make up the bulk of the file).

I know afl will eventually map out these opaque blobs as no-op chunks, but that's a very time-consuming process, especially when I already know exactly where the opaque blobs are located within a file.

Browsing through the code, I can think of two ways to achieve what I'm looking for:

1) pre-generating an initial state for an effector map.

Since the effector map is local for every queue entry, and only used during deterministic steps, it seems there are a lot of stages that wouldn't use this, and afl would go back to fuzzing the opaque no-op chunks.  Is that correct?  Or does that matter?  Is there a way to determine whether the current queue entry is from a deterministic stage, and can apply the initial state effector map? If afl is given an initial state of the effector map, can it apply that to the bitflip stages that currently happen prior to the effector map's initialization?  What are the contents of the effector map (I'm still looking at the source, here)?

2) hooking up a post handler.

This seems like it might be a more flexible solution.  For starters, it's run on every mutation under consideration, not just the deterministic stages.  That could be handy if running custom mutators. However, the post handler is only given a buffer of data and its length, so in the current form, a post handler is stuck trying to figure out what changed.  Is it possible for afl to tell the post handler what range(s) of bytes were modified from the original buffer?  Well, I mean, yes, it is with the right patch, but does it make sense?  Obviously, it wouldn't make sense for splicing mutations, where the buffer no longer aligns with the original file. Where else would this fall apart?

What other gotchas are there for either approach?

**Comment by andreafioraldi** [comment]
Hi,
a simple answer is that you need a structural mutator. libprotobuf-mutator can be integrated as a custom mutator and used with AFL++.
Regards 1, I'm not an expert in deterministic stages, I prefer always FidgetyAFL, IDK how the effector map works, maybe Marc or Heiko know.
Regards 2 yes, with a post handler you can do simple structural mutations in this way:
Use initial seeds that are not the files that you use as input for your library, but encoded files.
Mutations are done on these encoded files that are decoded then in the post library.
For example, you can define the input as the metadata only and then insert the no-op chunks in the post handler.

**Comment by ammonriley** [comment]
>  define the input as the metadata only and then insert the no-op chunks in the post handler.

I hadn't thought of doing that.  Superficially, that seems like it would be perfect for some files, but a lot of insertions for others.  Certainly worth investigating.  

Is there a way the post handler can determine what the original input file is?  One of the issues I see here is that if I have test files A B and C, they'll all have the opaque blob no-op chunks in different locations.  I don't want to have to parse the metadata to re-insert the no-op chunks -- it would be easier if my post handler could read a sidecar file that defined where to do the insertions.  But to do that, I need to know which sidecar file to read.  This would be an issue with pre-generating effector maps, as well.

**Comment by vanhauser-thc** [comment]
do be honest I don't know what an effector map is :)

my initial response would have been:
a) either blacklist bytes not modify (e.g. by a command line option either as a pattern matching or byte offset definition) - that feature would need to be coded into afl-fuzz though
b) use a post handler that adds the data that is unnecessary

a) requires some coding, but is beneficial also for other users, plus gives some flexibility
b) is problematic because if the data finds a new path, the full data is put into the queue - and then that queue entry has all the big data that you did not want to have in it initially ...

now there is the additional issue that you have that the no-op chunks are not starting at a specific byte location ...
so maybe option c) or d) might be it:

c) coding in a pre handler additionally to the post handler that removes the chunks, then the mutation happens, then post handler adds the chunks again.
This would need a communication structure between pre and post though to be effective IMHO

d) coding in a queue handler, that modifies data that is added to the queue.

just some ideas, dunno if either of this is really a good solution

**Comment by vanhauser-thc** [comment]
> Is there a way the post handler can determine what the original input file is?

theoretically yes, as the queue filename hints that, but that information is not passed to the post handler (so would need to be added). could be done though. but does not sound like a good solution.

**Comment by vanhauser-thc** [comment]
@ammonriley what is your thinking or status on this? I am curious :)

**Comment by vanhauser-thc** [comment]
thinking about it, adding minimum and maximum length of mutated input and minimum offset from start and minimum offset from end could be useful.

**Comment by andreafioraldi** [comment]
I propose to expose havoc as a subroutine to the custom mutator so that you can parse the input in `afl_custom_queue_get` (maybe with a simple memem to find offsets) and apply havoc in a surgical way only on the parts of the input in which you are interested. I'll create a "custom mutator helpers" header that defines this special havoc (without chunk addition /deletion) and other useful helpers for 
the custom mutator like saving metadata in the output directory.

**Comment by andreafioraldi** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/dev/examples/custom_mutators/example.c#L64

You can now invoke this routine on a parte of the input to randomly mutatate it.

**Comment by vanhauser-thc** [comment]
Of course you can do this in a custom mutator. however it might be nice to have this as a standard feature as well so you can use radamsa, deterministic mutation etc. too

**Comment by vanhauser-thc** [comment]
this can be solved via a custom mutator so I am closing this
