### ISSUE TITLE
Small introduction/guide to fuzzing with AFL++

### ISSUE THREAD

**Issue by 20urc3** [AFLplusplus/AFLplusplus#1777]
Hello fuzzers !

I wrote a small introduction to fuzzing using AFL++ . Maybe it could be relevant in the tutorials.md doc :)
Link: https://bushido-sec.com/index.php/2023/06/19/the-art-of-fuzzing/

Cheers
2ourc3

**Comment by vanhauser-thc** [comment]
Hi, thanks for the PR.
I can see you made quite an effort in your blog post.
Sure I can add it to the tutorials, some errors I have seen:

```
Now let’s see this code snippet instrumented by AFL

sum:
    call __AFL_INIT
    call __AFL_START_LOOP
    call __AFL_LABEL_0
```
there is not really such code, it looks very different, so this is not helpful for the user IMHO.

```
cmin [[8] ](https://www.mankier.com/8/afl-cmin)– Minimizes the number of inputs provided based on those that reach the most path/are the most profitable for your fuzzing campaign.
    tmin [[9]](https://www.mankier.com/8/afl-tmin) – Allows you to optimize the corpus you have provided. It gets rid of duplicates, files that are too large or irrelevant.
```
you should call them afl-cmin and afl-tmin, otherwise the user will not find the tools. also tmin does not get rid of duplicates, that is what afl-cmin does. it only shrinks the files to the minimum possible without changed the coverage.

Mutation strategies is missing the "interesting value" type mutation, also splicing and inserting dictionary entries.
Also it does not do string mutation per se.

the sanitizer section is missing 1-2 sentences why these can be useful and why they slow down fuzzing and increase memory consumption.

Parallelism: we call them main and secondary now, not master and slave. and using parent + child is very misleading (and is used further down in the examples as well). 

I only read about 75% of it, these are the issues I have found so far.

**Comment by 20urc3** [comment]
Hi @vanhauser-thc ! Thanks for your answer and the feedback on the article.
Those changes are now implemented in the article :)
Cheers!
2ourc3

**Comment by vanhauser-thc** [comment]
done, thanks!
