### ISSUE TITLE
FairFuzz (afl-rb) integration 

### ISSUE THREAD

**Issue by dkasak** [AFLplusplus/AFLplusplus#18]
Has there been any discussion on incorporation of the [FairFuzz](https://github.com/carolemieux/afl-rb/) project by Caroline Lemieux into afl++? In my tests, its approach was very effective, certainly comparable in value to the aflfast schedules. 

That said, the code was slightly messy in a few places the last time I looked so perhaps it wouldn't be trivially mergeable and would require some manual porting.

What do you think?

**Comment by vanhauser-thc** [comment]
there are so many afl spinoffs its hard to find those which are really making it better, so any recommendation is helpful :)
I see that trunk was last updated in january and then there is the testcomp branch which has a lot of changes.
Do you know which one of the two would be better to use?

**Comment by dkasak** [comment]
From a quick look, I think the testcomp branch is just stuff related to the Test-Comp 2019 competition and isn't useful to us. I was using the master branch.

**Comment by hexcoder-** [comment]
Hi,
hexcoder- here,

no discussion yet, but I have been just looking into it.

My opinion is :
the byte mask to protect input structure
is a bit like light weight taint tracking
and I can imagine positive effects.

However in my earlier tests, I saw afl-rb stalled frequently,
and I don’t know if this has been resolved.
Do you?

Thanks, hexcoder-

Von: Denis Kasak <notifications@github.com>
Gesendet: Mittwoch, 17. Juli 2019 00:27
An: vanhauser-thc/AFLplusplus <AFLplusplus@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [vanhauser-thc/AFLplusplus] FairFuzz (afl-rb) integration (#18)


Has there been any discussion on incorporation of the FairFuzz<https://github.com/carolemieux/afl-rb/> project by Caroline Lemieux into afl++? In my tests, its approach was very effective, certainly comparable in value to the aflfast schedules.

That said, the code was slightly messy in a few places the last time I looked so perhaps it wouldn't be mergeable trivially cleanly and would require some manual porting of patches (particularly so because afl++ continued to evolve from afl, on which both were based).

What do you think?

**Comment by dkasak** [comment]
I used to experience some instabilities when I first started playing with it (about two years ago), including stalls. I submitted a few patches and some other problems were fixed by the author. I don't think any of those handled the stalls specifically, but they stopped happening at some point. There is still [an open issue](https://github.com/carolemieux/afl-rb/issues/2) regarding this, with a plausible explanation that it might be related to non-deterministic program behaviour on some test cases.

That said, a colleague and myself have been using FairFuzz heavily for the past year and it's pretty robust now.

**Comment by hexcoder-** [comment]
ok, i will consider it, after some more testing. Might take some time, though.

**Comment by vanhauser-thc** [comment]
I did some coverage and speed testing today, running it for 75 minutes against tiff and unrar. and comparing it against afl and aflfast.

fairfuzz. is. slow. like really slow. tiff: 40% speed loss (!!!), unrar 27% speed loss.

and for tiff it had less coverage than aflfast and afl.
in unrar however it had the most coverage.

so speed-wise it is very bad.
coverage-wise is can be very good or very bad.

not sure what to do with this to be honest.

opinions?

**Comment by dkasak** [comment]
FWIW, FairFuzz found some bugs for us that other fuzzers did not. We've found it to work best in conjunction with other afl instances (such as aflfast) in the same sync dir so they can share results.

**Comment by vanhauser-thc** [comment]
@dkasak how long did you need to fuzz until fairfuzz found it?

If its feasible to redo the tests, use afl++ with afl-fuzz -L 0   ... maybe MOpt can find it too, its insane how the paths explode

**Comment by vanhauser-thc** [comment]
@hexcoder- can you also please have a look?

its feasible to insert fairfuzz, but its quite a bit of work.

**Comment by dkasak** [comment]
The details are murky in my memory since it was some time ago and it wasn't our goal to benchmark fuzzers so it wasn't a very controlled experiment. It's not really feasible to reproduce the same conditions, unfortunately.

I'm planning on testing MOpt soon, though.

**Comment by dgaletic** [comment]
Hi, dkasak's collaborator here.  In my experience, FairFuzz had a superior number of `own finds` when used on an already heavily fuzzed target, i.e. a mature corpus, in slave instances with switches `-q 1` and particularly `-q 3`, in comparison (and syncing) with aflfast. The results would often be something like a dozen `own finds` for aflfast instances and 50-60 for FairFuzz after hours or maybe even a day of fuzzing.

I've also used it successfully in combination with LAF patches, though I don't remember the exact numbers. I can retest it with that same corpus if you'd like.

**Comment by vanhauser-thc** [comment]
@dgaletic if you could do some retesting and compare it with -L 0 option (MOpt) that would be very helpful.

If MOpt is able to find the same crashes at a similar - or faster - time, then fairfuzz would not much add to the table. I want to prevent that X different things are in the project that all do the same thing with same or less effectiveness.

if it does however find stuff MOpt cant then I would add it in.

**Comment by vanhauser-thc** [comment]
Out of bordeom I created a branch for fairfuzz and started integrating it.
I think I am about 2/3 through and it changes a LOT. not just specific functions that are called instead of vanilla afl, but also rewriting how the mutator stages work.
Basically fairfuzz does not just add scheduling, it changes internal behaviour even for normal af if fairfuzz is not activated.

overall - this has so many code changes - and I already removed quite some features - I dont see it feasible to add it without impact the overall performance of afl.

to get an idea of the changes - this is the diff to afl-2.52b with all additional options already removed

[fairfuzz.diff.txt](https://github.com/vanhauser-thc/AFLplusplus/files/3406122/fairfuzz.diff.txt)

**Comment by dkasak** [comment]
Yes, this is what I meant by it being a bit messy in places. I think you've convinced me it isn't worthwhile just trying to import the code as is. Which sucks, because if the techniques in Fairfuzz have merit, it would be nice to be able to combine them with all the additions in afl++.

**Comment by vanhauser-thc** [comment]
Well the good thing with the overall afl design is that you can run a lot of other fuzzer in parallel, like Angora, FairFuzz, etc.
And several other tools cant be integrated in afl++, again like Angora

Integrating is then a good move if what is integrated and/or what is new in afl++ can benefit from each other. For Fairfuzz this would not work, as its not only a different scheduler, its also a different mutator, and using fairfuzz means that most of the other afl-fuzz enhancements cant be activated (e.g. MOpt or AFLfast).
You can still use llvm_mode from afl++ and use that binary with FairFuzz.

So its not lost, its just an extra program. Like Angora.

@dkasak But I am keeping the branch with 2/3 of the work done, I also put a marker in afl-fuzz ("// XXX BUG TODO") until where I got and the fairfuzz.diff.txt is also in there. So if you want to - you can do the last 1/3 and then you would have an updated FairFuzz at least.

**Comment by vanhauser-thc** [comment]
I think its helpful to keep this open for other people to read and understand the reasoning, so I would recommend not to close the issue/request

**Comment by dgaletic** [comment]
Seeing as this is decided, I'm cutting my test short, but here are the results so far in case anyone's curious.

I ran 4 slave instances of afl++ and 4 of FairFuzz, all 8 using the same sync dir, on an already heavily fuzzed target compiled with all 3 LAF options enabled. Comparing totals, FairFuzz was somewhat slower (factor of 0.85) but had significantly more finds (factor of 1.51). No crashes were found, but that's not surprising given the state of the target.

| fuzzer   | settings              | own finds | total execs | runtime |
|----------|-----------------------|-----------|-------------|---------|
| afl++    | -L 0 -p fast -S s1    | 347       | 4.18M       | 3h 20m  |
|          | -L 0 -p fast -S s2    | 312       | 3.57M       |         |
|          | -L 0 -p explore -S s3 | 114       | 4.90M       |         |
|          | -L 0 -p coe -S s4     | 187       | 4.64M       |         |
|----------|-----------------------|-----------|-------------|---------|
| total    |                       | 960       | 17.29M      |         |


| fuzzer   | settings              | own finds | total execs | runtime |
|----------|-----------------------|-----------|-------------|---------|
| fairfuzz | -q 3 -S ff1           | 332       | 5.07M       | 3h 20m  |
|          | -q 1 -S ff2           | 249       | 3.03M       |         |
|          | -q 3 -r -S ff3        | 428       | 2.52M       |         |
|          | -q 3 -r -S ff4        | 442       | 5.11M       |         |
|----------|-----------------------|-----------|-------------|---------|
| total    |                       | 1451      | 14.73M      |         |

**Comment by vanhauser-thc** [comment]
@dgaletic  thanks a lot for this!

for me the results kinda make not much sense: fairfuzz with -q1 -r is faster than -q1, however -q3 -r is slower than -q3.  In my own tests I used q1 (without -r) and do see the name massive performance drop here too (and even worse with -q3 -r).

What also makes no sense to me is how any of the fairfuzz slaves can have more executions in the same time than -p fast. fairfuzz has so much more extra code, and because of the extra finds (which also all take extra time) it should be that the execution time gets lower because deeper/longer paths are discovered and hence the execution of the target should take longer.

and for the -q part - does that even make sense if you have several "normal" afl running in parallel?

So for whatever I am able to interpret the results - at least for this specific target -r seems to generate way more findings.
The -r part of FairFuzz is very small, and could easily be integrated. do you guys think that is a feature that would also be beneficial for other modes like MOpt, -p fast etc.?

I will start a test with -q3 -r against one with  -p fast and one with  -L 0 on libtiff. and check out the results

**Comment by dkasak** [comment]
In a bit of a hurry right now, so just a short comment: on a target like mruby, it seems intuitive that a large part of the input can be "useless" with respect to coverage, but can incur a large slowdown. For instance, a relatively rare piece of Ruby code can be preceded or followed by a relatively boring loop with a large number of iterations.

Since `-r` works to prune everything aggressively except that part of the input which produces thesingle rare tuple ("branch") it is currently focusing on, it's not surprising that it might result in both a faster test case and a more productive one with respect to producing even more rare tuples (since all the unimportant bytes are elided).

I'm not sure whether `-r` is directly applicable to aflfast's schedules and/or MOpt; I'll have to skim the papers again. Unless I'm missing something, for it to work, there needs to be a concept of focusing on a rare tuple (or a small set of tuples) so that it can trim more than what afl's usual trimming routines trim. From memory, aflfast does keep track of rarity in some manner since it's expending more fuzzing energy on rarer paths.

**Comment by vanhauser-thc** [comment]
in case you want to play around a bit: I implemented just the -r trim option into afl++ .... already a lot of code, but by far not as much as the total fairfuzz. I hope I got things right as I had to do some changes. 
its in this branch: https://github.com/vanhauser-thc/AFLplusplus/tree/rare_trim
(and yes, I added the rarity analysis)

I am nearly done with my fairfuzz/afl++ tests on libtiff and unrar, with some interesting results. stay tuned.

**Comment by vanhauser-thc** [comment]
paging @richinseattle - this might be interesting for you. paths do not have anything to do with coverage - even from the same compiled binary


So my tests are done. I tested AFLfast, MOpt and all four FairFuzz modes.

MOpt -L0 has by far the most paths, way more than FairFuzz. *BUT* when looking at the coverage, MOpt is actually the worst. (and I should also say that MOpt has the most impact if between -L 10 and -L 60, in long running campaigns)

FairFuzz has a 35-70%(!) speed loss. However when looking at the coverage it is the best, especially -q3

e.g.: libtiff (all ran for 92 minutes, the coverage is the number of lines hit, done with afl-cov):
FairFuzz -q1 -r
paths_total       : 1411
exec/s            : 820
coverage          : 5033

afl++ -L0
paths_total       : 2604
exec/s            : 2031
coverage          : 1409

and basically the same for unrar.

however one thing which is specific for unrar: of the 6 testcases, FairFuzz -q3 was the only one which did not have a 100% stability but just 31%

So FairFuzz is really strong

**Comment by dgaletic** [comment]
Thanks for looking into and implementing this so quickly! I'll spin up a bunch of afl++ instances with and without `-r` and let them run for a day or two, then get back to you. I'll do it without `-r` first in case you need to push more changes into the experimental branch today.

> for me the results kinda make not much sense

I wouldn't worry about the speed discrepancies from my test; I saw them happen regularly when fuzzing mruby even when the fuzzers had identical settings, e.g. two `aflfast -p fast` instances where one was 40-50% slower. Discrepancies in `own finds` were also common. Unfortunately, I hadn't noted how just the `-r` tended to affect speed and finds overall. Given the discrepancies, we'd need many more samples for reliable conclusions, but hopefully my new test with just afl++ nudges us towards that.

**Comment by vanhauser-thc** [comment]
@dgaletic I got a crash when running with -r so let me first find and fix the crash :)

**Comment by vanhauser-thc** [comment]
@dgaletic ok fixed the crash :)

**Comment by dkasak** [comment]
> however one thing which is specific for unrar: of the 6 testcases, FairFuzz -q3 was the only one which did not have a 100% stability but just 31%

This shouldn't happen unless it managed to stumble on a non-deterministic test case for unrar (or there's a very serious bug in the fuzzer, but I've never seen this).

**Comment by vanhauser-thc** [comment]
@dkasak the queue/.state/variable_behavior directory contains 322 files

**Comment by dgaletic** [comment]
@vanhauser-thc looks like a crash is still present in 584255d7b2016438a34789d8293d32d49653f1b3, my instances crashed after about 40 minutes.

**Comment by vanhauser-thc** [comment]
@dgaletic I put it in the README of the branch - it should all work without problems, except the -L MOpt mode. There it will crash as I havent it implemented there (different mutator).
if crashes in normal or -p fast etc. modes -  then there is a bug. I tested for 2 hours and had no crash

**Comment by carolemieux** [comment]
Hi! Just saw this. If you are still interested in integrating FairFuzz into afl++, I can help shepherd.

**Comment by vanhauser-thc** [comment]
@carolemieux me, I am using coverage (functions and lines of code reached) with afl-cov to compare, as paths discovered is pretty much meaningless, see https://github.com/vanhauser-thc/AFLplusplus/issues/18#issuecomment-513205016

After testing fairfuzz I must say I like it a lot. It achieves a high coverage even though it is slow when comparing the same runtimes.

The problem is though that is changes many parts and this makes (a) integrating future features difficult, (b) splitting up functionality more complicated (so e.g. just the mutatorsr can be used on its own by a different project) and (c) we already have additions (-L MOpt feature) which would need specific handling as it is a mutator of its own so getting fairfuzz functionality in there would need someone who really know what he is doing (understands the internal of fairfuzz, the how and why)

As I see fairfuzz really making a fuzzing campaign better, I am opening up to the idea again to have it integrated but I know that I would not have the deep understanding. and the person who would would desperately need that.

**Comment by carolemieux** [comment]
Thanks for the context, everyone. 

Before we jump in to integrating FairFuzz, maybe we should get on the same page about whether it fits into the goals of AFL++. So, this is a little bit of a long comment on my end to make sure we're on the same page. 

The key point of FairFuzz is to try to get more inputs hitting rare branches (branches hit by few fuzzer-generated inputs). It modifies the mutation strategy in order to accomplish this. The key components are to
1) Select inputs hitting rare branches as inputs to be fuzzed [queuing]
2) Build a mutation mask that designates which branches in the input can be fuzzed [masking]
Thus, you can think of FairFuzz as kind of a "depth-first" fuzzer that really tries to drill down into rare branches. When run individually, FairFuzz tends to be strongest on programs with highly nested branch structure. For other programs, FairFuzz may still be useful, but I believe @dkasak's use-case of using FairFuzz as one fuzzer in a portfolio of fuzzers (see also "EnFuzz: Ensemble Fuzzing...").

The `-r` feature of FairFuzz is not key.** This trimming was done in an attempt to bring down time cost when FairFuzz selects very long inputs to fuzz---because the branch mask computation requires a pass over all the input, the input being smaller. An alternative, which I experimented with in FairFuzz but didn't make it to the main branch, is simply to compute approximate time it will take to compute the branch mask, and if this is too long, skip the computation and go straight to the havoc fuzzing stage. This is maybe less intellectually satisfying, but pretty easy to code :)

The `-q` features are various attempts on my end to make FairFuzz break out of the limitations of its depth-first nature. In my experiments I found that in the long run, e.g. `-q 3`, just ends up converging to AFL-like coverage. Another alternative `-q` which I did not implement is to come up with some threshold of branch rarity `R`, and then only do the whole targeting of rare branches when rare branches are hit by fewer than `R` inputs. Of course, the optimal `R`

So... if you are looking to build a single best-of-fuzzer, I can't say whether adding FairFuzz integration will play nicely with all the other features. It should interact fine with AFLFast, I believe, if AFLFast's queueing tends to select inputs hitting rare branches anyway. I will look through MOpt a little and see whether in conflicts there. I think a reasonable option to enable is something like `--fairfuzz R` which enables fairfuzzing only when new branches are hit by fewer that `R` inputs, and then reverts to non-fairfuzz mode to explore after that. 

On the other hand, if you're looking to build a fuzzer which can have all these modes for ease of parallel fuzzing, then we could incorporate full FairFuzz.

Let me know what you all think of this. 

** I did some statistical experiments, post-paper evaluation, and found that (over 6 hours) the queueing and masking stages were key to increasing coverage on most of my benchmarks, but the `-r` trimming stage was not.

**Comment by carolemieux** [comment]
I've taken a look through the MOpt paper + code. As has been suggested above, it looks like it would not play nicely with FairFuzz. In particular, because MOpt makes use of pilot fuzzing sessions to try to optimize mutation operators, whereas FairFuzz's whole goal is to skip creating mutants that don't hit the rare branch.

The only sensible integration I can think of would be to enable the branch mask during the `core fuzzing stage` of MOpt, if the parent input hits a rare branch. 

Out of curiosity, have you all experimented with these afl++ optimizations vs. the `-d` setting of vanilla AFL? In my [evaluation](https://www.carolemieux.com/fairfuzz-ase18.pdf), it tends to vastly outperform AFL (see Figure 3) by, as the MOpt paper points out, skipping the deterministic mutation stage. I didn't see any mention of it in the options above.

**Comment by vanhauser-thc** [comment]
@carolemieux I will get back later to this - so far thank you very much for your input.

IMHO not all features must be able to work together. MOpt is an own mutator so it cant work with different mutators. Fairfuzz is a mutator and scheduler so it does not work together. 

Fairfuzz makes a lot of code changes in several areas of afl-fuzz ... thats kinda my worry, that it is difficult to get right (because there are differences to the stock afl) and it makes future integration of features difficult as well (someone needs to understand how to apply fairfuzz to these)

IMHO fairfuzz is really good, but to be used as an addition to a fuzzing campaign (-S slave3), not running alone.

**Comment by dgaletic** [comment]
Here are some new test results. I wanted to try out afl++ with `-r` and make some comparisons with afl++ and FairFuzz (afl-rb). Since the `-r` experimental branch doesn't work with `-L 0`, I ran the master branch without it too. 

I tested three configurations. In each, the fuzzer instances were syncing with each other (but not across configurations). Each configuration was tested for 6 hours. All instances were slave instances. I had:

a) eight instances of afl++ (4x -p fast, 2x -p coe, 2x -p explore)
b) eight instances of afl++ with -r (same -p values)
c) eight instances of afl-rb (two of each: -q 1, -q 3, -q 1 -r, -q 3 -r)

For each configuration, each instance's `queue/` files were collected and minimized with cminimize.

```
Starting corpus coverage: 732558 tuples
afl++ coverage:  737258 (+4700 tuples, +0.641% increase)
afl-rb coverage: 737754 (+5196 tuples, +0.709% increase)
afl++ with -r  : 736403 (+3845 tuples, +0.524% increase)
```

(incidentally, it correlates with the `own finds` (`paths_found`) metric even if that one is less precise: 3168 for afl++, 3427 for afl-rb, and 2277 for afl++ with `-r`)

I realise the discoveries don't look like much in relative terms, but that is because the starting corpus is very mature.

If anyone's interested in other metrics, I have the instances saved, so let me know.

@carolemieux:
> Out of curiosity, have you all experimented with these afl++ optimizations vs. the -d setting of vanilla AFL? In my evaluation, it tends to vastly outperform AFL (see Figure 3) by, as the MOpt paper points out, skipping the deterministic mutation stage. I didn't see any mention of it in the options above.

This (`-d`) is the same (AFAIU) as using slave (`-S`) instances. Your observation seems consistent with our own and the recommendation in `docs/parallel_fuzzing.txt`. @dkasak and I would always fuzz in parallel mode, typically using a single master (`-M`) instance and as many slave instances as we could squeeze in. Recently I've been running slave instances exclusively, with occasionally (e.g. once a month or less) turning those off to run the experimental parallel masters mode for a few days.

Another thing to mention since we're comparing fuzzers: I'd noticed afl-rb used much more memory than aflfast, but had chalked it up to me using a very large map (MAP_SIZE_POW2 19) in those instances. Since I was already comparing it to afl++ now, I explicitly checked. I found that afl-rb's memory usage grew very quickly when increasing map size, while aflfast's and afl++'s did not. I don't see any mentions of memory usage in your paper so I was wondering if this was a known and necessary thing for afl-rb to work its magic or perhaps an issue.

Specifically, with map size 19, afl-rb used about 2.4 GiB per instance, afl++ with `-r` used 1.5 GiB, while afl++ and aflfast used about 300 MiB.
With map size 17, afl-rb used about 600 MiB, or 3.9 times less memory, which correlates with the map size being 4x smaller. I haven't checked the other fuzzers with 17. Perhaps also worth noting that afl-rb used the same amount of memory with and without `-r`, while afl++ used more memory only with `-r`.

**Comment by carolemieux** [comment]
@dgaletic Ah, yes, `-S` does the same as `-d`. Forgot that :)

Re: memory usage. Interesting. I have not encountered this, but I have not carefully examined the memory usage of FairFuzz. FairFuzz adds the extra map to keep track of the number of inputs hitting branches, (array of u64's of MAP_SIZE length), but that doesn't explain 1+ GB of memory. Besides the `-r` option in `afl++`  doesn't have the same issue.  

My guess is that the memory usage is driven by the fact that the trace_minis are kept around for each input (see line 1579 of afl-fuzz.c in FairFuzz). If your map size is 2^19, the mini trace is 2^16 bytes == 64 KB for each input. So if your queue has a large number of inputs, that would explain it.  The alternative to keeping this around is just to re-run inputs, which should not impact performance too badly. If you want me to explore this more, we can move this convo to an issue on afl-rb repo.

**Comment by vanhauser-thc** [comment]
@dgaletic so the -r option actually hurt afl++ if I interpret the result correctly?

in my two test cases I had both, in one it helped (unrar) and in the other it was worse (libtiff).

**Comment by vanhauser-thc** [comment]
with the current state of afl++ and the large area of change that fairfuzz brings I dont see it a good move to implement :-(
well it can still run as a slave and bring good new paths.
also I added a -p schedule target that should help concentrate on rare branches.
so closing this for now.

**Comment by jiliguluss** [comment]
> in case you want to play around a bit: I implemented just the -r trim option into afl++ .... already a lot of code, but by far not as much as the total fairfuzz. I hope I got things right as I had to do some changes. its in this branch: https://github.com/vanhauser-thc/AFLplusplus/tree/rare_trim (and yes, I added the rarity analysis)
> 
> I am nearly done with my fairfuzz/afl++ tests on libtiff and unrar, with some interesting results. stay tuned.

Hello, I have also paid attention to fairfuzz recently. I hope to guide fuzz to break through the rare branch and obtain higher code coverage. 
I use AFL++ instead of AFL. I hope to use fairfuzz in AFL++, thank you very much for the work, but I find that the `rare_trim` branch has been removed.
Can this branch be restored?  Do you have any other suggestions for solving the rare branch problem with afl++?
Hope for reply, thanks very much.

**Comment by vanhauser-thc** [comment]
@jiliguluss It would make no sense to restore the branch, because AFL++ has evolved so much that you would be missing a lot. simply add the original fairfuzz as a secondary fuzzer to your compaign

**Comment by jiliguluss** [comment]
> @jiliguluss It would make no sense to restore the branch, because AFL++ has evolved so much that you would be missing a lot. simply add the original fairfuzz as a secondary fuzzer to your compaign

Thank you for your answer. So, in recent years, has AFL++ integrated any new features to address the rare branch problem?
