### ISSUE TITLE
unicorn mode compilation fails because of PEP 668 

### ISSUE THREAD

**Issue by nitrogar** [AFLplusplus/AFLplusplus#1846]
**Describe the bug**
the build command "make distrib" fails in building unicorn mode because "pip install " does not work after PEP668.

**To Reproduce**
1. install archlinux
2. clone and make distrib
3. error

**Expected behavior**
well it should compile ...

**Screen output/Screenshots**
![image](https://github.com/AFLplusplus/AFLplusplus/assets/53944555/0e393025-1d48-4db5-ae33-9a1a5a2733df)

**Additional context**
the error caused by this lines

![image](https://github.com/AFLplusplus/AFLplusplus/assets/53944555/49011654-d392-44ad-be33-f0b7299a5297)

**Comment by domenukk** [comment]
Looks like you have to install `pipx` and alias `pipx` to `pip`?
I don't think there is much we can do from unicornafl's side - you want to install from local but you're not allowed to..

Or do you have a better idea?

**Comment by vanhauser-thc** [comment]
@domenukk  no the issue is that our scripts use pip which is not available anymore, so we need to update

**Comment by tylzars** [comment]
Not that it's the right solution but it this can be fixed by adding `--break-system-packages` in `./unicorn_mode/build_unicorn_support.sh` on lines 204, 207, 214, 217 to the PIP install command after the other flags. 

I did a brief test with `pipx` but it doesn't seem set up for the install AFL++ is trying to do.

**Comment by vanhauser-thc** [comment]
fixed.
