### ISSUE TITLE
Segmentation Fault in backtrace() when using frida mode

### ISSUE THREAD

**Issue by uriyay** [AFLplusplus/AFLplusplus#1903]
**Describe the bug**
When using frida mode and calling backtrace() a segmentation fault is triggered.

**To Reproduce**
```bash
$ cat <<EOF > test.cpp
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <sys/types.h>
#include <unistd.h>
#include <execinfo.h>

#include <vector>

extern "C" void crashme(char *buf, size_t size);

void fuzz(char *buf, size_t size)
{
    crashme(buf, size);
}

int main(int argc, char *argv[])
{
    FILE *f = fopen(argv[1], "r");
    fseek(f, 0, SEEK_END);
    size_t len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = (char*)malloc(len);
    size_t n_read = fread(buf, 1, len, f);
    fclose(f);

    fuzz(buf, len);
}
EOF
$ cat <<EOF > shared.cpp
#include <stdio.h>
#include <stdint.h>
#include <sys/types.h>
#include <unistd.h>
#include <execinfo.h>

#include <vector>

extern "C" void crashme(char *buf, size_t size)
{
    std::vector<void*> callstack(50, nullptr);
    if (size >= 2) {
        if (buf[0] == 'A') {
            if (buf[1] == 'B') {
                printf("going to call backtrace!\n");
                backtrace(callstack.data(), static_cast<int>(callstack.size()));
            }
        }
    }
}
EOF
$ g++ -shared shared.cpp -o libshared.so
$ g++ g++ test.cpp -L ./ -lshared -o test
$ echo -ne "AB" > crash.bin
$ LD_PRELOAD=AFLplusplus/afl-frida-trace.so LD_LIBRARY_PATH=./ ./test ./crash.bin
going to call backtrace!
Segmentation fault
$ LD_LIBRARY_PATH=./ gdb -q --ex "set environment LD_PRELOAD=AFLplusplus/afl-frida-trace.so" --args ./test ./crash.bin
Reading symbols from ./test...
(No debugging symbols found in ./test)
(gdb) run
Starting program: test ./crash.bin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
going to call backtrace!

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff706f83e in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007ffff706f83e in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007ffff707159b in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007ffff74c2da3 in __GI___backtrace (array=<optimized out>, size=50) at ./debug/backtrace.c:78
#3  0x00007ffff75ca86a in crashme () from ./libshared.so
#4  0x00007ffff6f0173a in ?? ()
#5  0x0000000000000002 in ?? ()
#6  0x0000555555571490 in ?? ()
#7  0x00007fffffffddf0 in ?? ()
#8  0x00005555555552ef in main ()
Backtrace stopped: frame did not save the PC
(gdb)
```

**Expected behavior**
backtrace() should not crash

**Additional context**
I encountered this behavior when trying to fuzz a something with frida mode and using the flag AFL_INST_LIBS=1.
I ran it with AFLplusplus commit id = f596a297c4de6a5e1a6fb9fbb3b4e18124a24f58, compiled on x86-64 Ubuntu 22.04.2 on WSL (5.15.90.1-microsoft-standard-WSL2).

**Notes**
I thought maybe setting AFL_FRIDA_EXCLUDE_RANGES=libgcc_s.so.1 will solve the problem but it didn't work (maybe writing a frida hook for backtrace() might be a workaround)

**Comment by vanhauser-thc** [comment]
@WorksButNotTested

**Comment by WorksButNotTested** [comment]
When running C++ code in Stalker, exception handling gets tricky, since the frame information for unwinding references function addresses, however, with stalker, we aren't running the original code, but rather an instrumented copy elsewhere in memory. As a result without intervention, the c++ exception handling logic wouldn't be able to handle exception and branch correctly to `except` or `finally` blocks. Therefore FRIDA needed [this](https://github.com/MissingFuzz/frida-gum/blob/0c971f2430daf742b30d1a1b49e3f09a96aba6a4/gum/backend-x86/gumstalker-x86.c#L876) modification to make things work. However, I've not looked at how `backtrace` works or tried to support it since I haven't come across it being a problem before.

In many cases, it will only be used by a crash handler for example and so removing the crash handler or replacing it with a call to either `abort` or `exit` is usually better for performance anyway. As you say though, simply patching out the call should solve the problem. You could either use the [scripting](https://github.com/AFLplusplus/AFLplusplus/blob/stable/frida_mode/Scripting.md) support or otherwise `LD_PRELOAD` a library to patch your binary at runtime, or just patch it statically by editing the file.

Hope that helps.

**Comment by uriyay** [comment]
Thanks, its more clear to me now.
I wrote a workaround frida's script that retrieves the callstack from Thread.backtrace:
```js
Afl.print(`In script.js`);

const backtrace = DebugSymbol.fromName('backtrace');
Afl.print(`backtrace = ${backtrace}`);
var callstack_ptr = 0;
var callstack_size = 0;
Interceptor.replace(backtrace.address, new NativeCallback((callstack, size) => {
    Afl.print("in backtrace hook!");
   //return 0; //if you don't want the backtrace
    var frida_backtrace = Thread.backtrace(this.context, Backtracer.ACCURATE);
    for (var i = 0; i < size; i++) {
        Afl.print(`i = ${i}`);
        if (frida_backtrace[i] != undefined) {
            callstack.add(i*8).writePointer(frida_backtrace[i]);
        }
    }
    return 0;
}, 'int', ['pointer', 'int']));
Afl.done();
```

**Comment by WorksButNotTested** [comment]
No worries. Glad you were able to get things working!
