### ISSUE TITLE
Name files by hash of their contents

### ISSUE THREAD

**Issue by smoelius** [AFLplusplus/AFLplusplus#2077]
Is there a way to name crashes, hangs, etc. by the hash of their contents, e.g., SHA1 or SHA256?

If not, is this something that you would be open to?

**Comment by vanhauser-thc** [comment]
That is what libfuzzer does. This looses interesting information like the source the crash was mutated on plus would break existing tooling.
Maybe as an option - why would you find that helpful?

**Comment by smoelius** [comment]
> why would you find that helpful?

It makes it easier to tell when a new input has been generated, e.g., in comparing runs of a target, or comparing runs of different targets whose inputs have the same structure.

If it were an option, would you imagine it enabled by a environment variable?

**Comment by vanhauser-thc** [comment]
But if another instance finds the same bug it highly likely has a different hash because of different length or different bits through mutations.
The crash deduplication in afl in minimal and only per instance but imho effective. Naming files by content hash will only in a few cases help, but loosing interesting information plus creating incompatibilities with important tools like casr-afl - the best tool for crash deduplication.

If you still think that this change would help you (which i honestly doubt :) ) then send a PR. Yes it should be an env.

**Comment by smoelius** [comment]
I see that the repo already contains a SHA1 implementation: https://github.com/AFLplusplus/AFLplusplus/blob/ad0d0c77fb313e6edfee111fecf2bcd16d8f915e/custom_mutators/libfuzzer/FuzzerSHA1.cpp#L69

To avoid to having two implementations, I'm going to move that code into a `src/afl-sha1.c` file, and have `custom_mutators/libfuzzer/FuzzerSHA1.cpp` refer to it. Ok?

**Comment by SonicStark** [comment]
Give a try to `AFLplusplus/include/xxhash.h`, which can be used directly in those main components of afl++.

**Comment by vanhauser-thc** [comment]
@SonicStark I think this defeats the purpose to see if a libfuzzer instance found the same crash or not (but as I said, IMHO this will rarely have any use anyway).

@smoelius please keep the sha1 implementation as this is a download of libfuzzer which I will update at some point and then things break. just put the best sha1 that you find into src/afl-performance.c.

**Comment by smoelius** [comment]
Hmm. Not sure why this didn't automatically close.
