### ISSUE TITLE
Cmplog in qemu_mode

### ISSUE THREAD

**Issue by wideglide** [AFLplusplus/AFLplusplus#328]
I have two instances of AFL++ 2.64c fuzzing file and pcre2 trying to use the RQ/cmplog functionality with qemu_mode.  The fuzzer seems to be having success with the colorization stage, but no success for the input-to-state stage.  Is there a good way to determine if the input-to-state stage is working correctly?   Seems like the ITS stage should have had some finds by now?

stats after 18 hours:
pcre2: `custom/rq : 0/0, 0/0, 229/799k, 0/627`
file: `custom/rq : 0/0, 0/0, 101/364k, 0/4635`

pcre2 command line:
```
/usr/local/i386/afl-fuzz -Q -i inputs -o outputs -m 4096 -t 2000 -c 0 -S pcreB5000 -- ./bin/pcre2grep -f @@ ./share/passwd
```

file command line:
```
/usr/local/i386/afl-fuzz -Q -i inputs -o outputs -m 4096 -t 2000 -c 0 -S fileB6000 -- ./bin/file -Lm ./share/misc/magic.mgc @@
```

**Comment by andreafioraldi** [comment]
Hi, can you try the dev branch? Btw, how large are your testcases?

**Comment by andreafioraldi** [comment]
In general, if your initial corpus is very good input-2-state is not needed. Try to start with a single testcase and see what happens.

**Comment by andreafioraldi** [comment]
With readelf is working: `   custom/rq : 0/0, 0/0, 24/277, 29/2433 `
With file is not working.
This is due to, I guess, the fact that file doesn't use CMP instructions but a lookup table or a switch-case to compare magic bytes. Switch-cases are not handled in QEMU but are transformed to if-else in LLVM mode during compilation.
