### ISSUE TITLE
malloc_usable_size in libdislocator leaks memory

### ISSUE THREAD

**Issue by nataraj-hates-MS-for-stealing-github** [AFLplusplus/AFLplusplus#348]
I am using ```libdislocator``` to trace memory problems

In my project ```malloc_usable_size``` is used when it is built in some modes.

When I came to testing these modes, I was happy to find out, that ```malloc_usable_size``` have been recently implemented in ```libdislocator```

But after running it, I found out, that some tests started to fail with "Out of memory" failure.

I've double checked with standalone program
```
#include <malloc.h>
#include <stdio.h>

int main(void)
{
  char * p;
  int i,j;
  for (i=0;i<1000000000;i++)
  {
    printf("%i\n",i);
    for (j=0;j<100000000;j++)
    {
       p = malloc(42);
       fprintf(stderr,"%i\n", malloc_usable_size(p));
       free(p);
    }
  }
}
```
If you run it with ```LD_PRELOAD=/home/nataraj/dev/libdislocator.so ./a.out 2>/dev/null```
and will `watch free` in other console, you will see, that free memory will constantly decrease. 

So, if you are using ```malloc_usable_size``` in really intensive way, you really can get Out of Memory error.

I've been trying both ```dev``` and ```master``` branches, with same effect

**Comment by domenukk** [comment]
Hey, thank you for your report.
What you're experiencing is actually the behavior of libdislocator, see: 
https://github.com/AFLplusplus/AFLplusplus/blob/c7de368dc20078116bcb2e34b0f2237127802841/libdislocator/libdislocator.so.c#L353

It never actually frees, so that use-after-free bugs will be detected.
I guess the idea is that at the end of the comparably short run, the memory is reset, anyway.
One easy fix could be to give your testcases more (or even unlimited, `-m none`) memory.
In case that doesn't help, libdislocator will have to be adapted to your use case. Of course, you may lose/lessen the UAF detection, then.

**Comment by vanhauser-thc** [comment]
maybe "USE_ASAN=1" will be better for your target if you run out of memory and your -m value you need is getting too high (but ASAN memory requirements are high too :) )

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Thanx!
This all added more understanding about what is happening...
