### ISSUE TITLE
question: why trace-pc-guard is better?

### ISSUE THREAD

**Issue by wideglide** [AFLplusplus/AFLplusplus#397]
Do you have additional details/ insight as to why trace-pc-guard is a [better default](https://github.com/AFLplusplus/AFLplusplus/pull/374/commits/5d0bcf8152136df83337c8ae9808d2aacc1e6693) in llvm mode?  

I looked around for some comments in issues or commits, but didn't see the reasons why.  I would suspect this is a finding from Fuzzbench, but I'm curious why it works better.

If there's a better place for this discussion, please let me know, thanks!

**Comment by vanhauser-thc** [comment]
Originally pcguard was very slow, it instrumented every block, etc.
However somewhere in the llvm versions they rewrote that and now do the same as InsTrim is doing - with less bugs though (compared to classic afl instrumentation instrim looses a bit of coverage, on the other hand it is 20% faster). so it has good coverage, and - that is surprising to me, the speed is also good (which does not make sense to me when I look at the disassembly).
The only thing better than pcguard is LTO, but that requires llvm 11 and can be more difficult to get running.
ngram-x and ctx can also be very good, but this is target dependent.

**Comment by vanhauser-thc** [comment]
OK, here is a result.
This was actually not easy to build the fuzzbench benchmark targets with lcov coverage so that they give meaningful results. Only one in the end compiled correctly:

|BENCHMARK|FUZZER|LINES|BRANCHES|PC|
|:-:|:-:|:-:|:-:|:-:|:-:|
|freetype2-2017|aflplusplus_classic|965|352|1758|
|freetype2-2017|aflplusplus_nosingleblock|965|352|1756|
|freetype2-2017|aflplusplus_nozero|943|345|1756|
|freetype2-2017|aflplusplus_nozerosingleblock|805|289|1735|

The PC column is the edge count that comes from sancov.
LINES and BRANCHES come from lcov.
We see that there are differences, where the PC values are the same there are differences in the LINES and where are the same number of lines there is a difference in the PC values.
@jonathanmetzman

lcov was done with a copy of afl/fuzzer.py with the following changes in build:
```
cflags = ['-fprofile-arcs', '-ftest-coverage', '-O3']
utils.append_flags('CFLAGS', cflags)
utils.append_flags('CXXFLAGS', cflags)
os.environ['FUZZER_LIB'] = '--coverage /libAFL.a'
```

**Comment by jonathanmetzman** [comment]
Thanks for trying this.
I think `os.environ['FUZZER_LIB'] --coverage /libAFL.a'` is problematic for FuzzBench. Many benchmarks depend on this being a library rather than arguments to the linker. I assume this is why most benchmarks couldn't build.

[Clang's source based coverage](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html) is used in OSS-Fuzz so i think it is supported much better by FuzzBench benchmarks. I think it would also be a good independent sanity check.

We might replace SanitizerCoverage for determining coverage as we have plans to use source-based coverage for enhancing what we can report about coverage (e.g. we could do reports that show coverage hit by one fuzzer and not another). Ruikang Shi (Will CC him when I get his Github username) is going to work on this feature this summer.
