### ISSUE TITLE
afl-clang-lto has issue with persistent mode

### ISSUE THREAD

**Issue by Kyle-Kyle** [AFLplusplus/AFLplusplus#508]
I happened to find that sometimes the stability is not 100%(which is fine) but the instability always stays the same throughout the entire fuzzing.

By some debugging and patching, I found out that the stability drop is actually introduced by the edges: 1. entering __AFL_LOOP(right after `_afl_persistent_loop`) 2. exiting __AFL_LOOP. I don't think instrumentation for these two edges are necessary.They only introduces false instability.

And I also have several questions.
1. Is this flaw by design or just imperfect implementation in LTO mode
2. I'm using shared memory for input(not sure whether it it related). And I found two `_afl_persistent_loop` in my harness. Is this is intended by design? If yes, may I ask why?
3. Is there a way to disable instrumentation for a function or a file with AFLplusplus(any mode)? (I think I saw whitelist instrumentation somewhere, but here I wonder whether there is blacklist instrumentation)

Thanks!

**Comment by vanhauser-thc** [comment]
You should see the same issue with all instrumentation modes, so afl-clang-fast and all it's AFL_LLVM_INSTRUMENT options.
is that not the case for you?

It comes inherent with using the usage of afl-clang-* to compile the harness.
it does not matter if you use shared memory, stdin or files for the input.

There are ways around this however this is not easy for an user to perform.
but that is why I have not seen this ;)

for non-sancov/non-PCGUARD instrumentation this could maybe fixed in the instrumentation pass. would need to look at it.
I think that is the only useful way.

you can selectively disable instrumentation files and functions, it needs llvm 12 though. see llvm_mode/README.instrument_list.md

for stability and easy finding the functions see docs/FAQ.md

there is a good fuzzing discord with us, the fuzzbench people and many others there, its a great resource to discuss: https://discord.com/channels/736989425770168422/ or https://discord.gg/YdSdK8

**Comment by Kyle-Kyle** [comment]
Thank you so much for the information. It is very helpful. And it's very helpful to know there is a discord server for AFLplusplus. Hopefully, I won't be spamming it with noob questions ;)

I specifically mentioned `shared memory` because I saw the second `_afl_persistent_loop` call is introduced around the access to the input length.

**Comment by vanhauser-thc** [comment]
it is not only for afl++, also libfuzzer, fuzzbench, developing your own ... anything fuzzing related

**Comment by vanhauser-thc** [comment]
A fixed for LTO is in dev. please test.

The other primary mode - PCGUARD/sancov in afl-clang-fast can only be fixed by using a shim, e.g. like examples/aflpp_driver/ 

I could implement that too for other instrumentation types like CTX, instrim etc. but I consider them outdated and subpar compared to the two main ones, so I won't, also to discourage their use :)

**Comment by Kyle-Kyle** [comment]
It is amazing how fast you guys can fix things. I will try it tonight. Thanks!

**Comment by Kyle-Kyle** [comment]
I think it is fixed! Amazing. Now my fuzzing instance shows more reasonable stability metric. And I have better idea about the quality of my harness. Thanks!
