### ISSUE TITLE
Limiting command line options (-V -E) do not work properly

### ISSUE THREAD

**Issue by floyd-fuh** [AFLplusplus/AFLplusplus#52]
I was trying to fuzz a target only for a minute or until a certain amount of executions were done. However, afl-fuzz just went on fuzzing. For example:

`afl-fuzz -Q -i afl_in -o afl_out -M main -s 1 -E 100000 -V 60 /examples/binutils-2.24/build-clang/binutils/readelf -a @@`

Any idea why -E and -V are so unreliable?

**Comment by vanhauser-thc** [comment]
@floyd-fuh its because there is a big loop and these conditions (and others) are checked when its done. Thats why I will have several executions more or a longer runtime. but it should not be that much.

its a choice between fuzzing performance and accuracy of the options and I choose the performance (not sure though it would have a real impact though)

If you want you can have a look and move it inside and see how the impact is. it might add to the complexity too as the loop might be more complex then. dunno, has been some time :)

**Comment by floyd-fuh** [comment]
Thanks for the quick response Marc. Ok, I see your point. It's just that I run it with -V 60 and sometimes it seems like it won't stop at all and it is still running after 3 minutes. I'm preparing something that will serve as a demo of AFL and it would be very nice if we would have the ability to roughly say how long AFL should run. More on this later (I might send you a direct email about this).

On the other hand precision might be something that would be very important, when it comes to benchmarking I think it would be very nice if people could compare runs with -E 100000 for different settings. There performance is obiously important, but as long as all runs have the same -E/-V penalty that should be fine too.

So here's an idea: how about we either measure exactly or not at all? I think it would also be OK if -E and -V switched might impact performance *a little*, but not too much. As long as AFL has full speed when -E and -V are not specified I think it should be fine. So there are various possiblities, for example enable or disable -V -E at compile time or at runtime... depending on what the performance impact is.

I might look into moving it inside the loop, don't have an ETA yet though.

**Comment by vanhauser-thc** [comment]
the -E/-V were rather meant for larger values than 60 ;)

but you can also just use timeout ... timeout -s SIGINT 60 afl-fuzz ...

however you need to measure the time until the UI is up and add that to the 60.

PRs are welcome but wait a few days we have a big code refactoring up at the moment (-> code_cleanup branch) otherwise it wont be able to merge :)

**Comment by vanhauser-thc** [comment]
@floyd-fuh fyi - the big code refactoring and code indention change is done, now any PR is good :)

**Comment by vanhauser-thc** [comment]
@floyd-fuh thinking about it, the time limit implementation would be way more effective with alarm() was it would then be precise.

the number of execs though can not be made precise without a performance impact. so there checking after a queue entry is done (which can be lots of extra execs) is the only usuable way ...

**Comment by vanhauser-thc** [comment]
OK, alarm can not be used as afl uses this to see if the child times out. so I see on other way. damn.

**Comment by domenukk** [comment]
Fuzzing no longer uses `alarm()`. A precise -V could now be added to afl-fuzz.

**Comment by vanhauser-thc** [comment]
@domenukk thank you for the reminder! instead I implemented it in the UI which is called regularly and so they are now precise enough without having a noticable overhead.
