### ISSUE TITLE
Possible to use Mitigation_CFLAGS?

### ISSUE THREAD

**Issue by davidgith** [AFLplusplus/AFLplusplus#722]
Hello,
I want to build the [sgx-sdk](https://github.com/intel/linux-sgx) with afl but unfortunately it is prepared to build it with gcc. Therefore, it uses Mitigation_CFLAGS like -mindirect-branch-register and -mfunction-return=thunk-extern which can't be used by clang. But as far as I understand AFLplusplus, it works much better with clang. I already tried it with the gcc-plugin, but if it's possible, I would be happy to use the best version, or isn't there much difference between these two possibilities?
Does anyone have an idea, how to work with the CFLAGS with clang?
Thanks!

**Comment by vanhauser-thc** [comment]
the difference between the old afl-gcc and the newer afl-gcc-fast is that the newer has faster instrumentation and supports features like persistent mode, selective instrumentation.
llvm on the other hand additionally has solving capabilities (LAF, CMPLOG) and collision free coverage.
llvm is better my a long way.

however - there are targets that do not compile with llvm. not because of C*FLAGS but because of the code.

for your case I would recommend to remove all C*FLAGS that clang errors on, and see if you can work around potential remaining build errors.
without llvm support there is also no libfuzzer, honggfuzz etc. that you could use. which also means it is a target that is likely very little fuzzed ;)

**Comment by davidgith** [comment]
Thank you for your fast reply and explanations!
If I remove these FLAGS, I get an error with implicit conversion changing signedness from int to unsigned long.
But these are obviously no errors caused by afl, so I try to work on it;)

**Comment by domenukk** [comment]
Enjoy :)
