### ISSUE TITLE
afl-cmin not working with -f flag

### ISSUE THREAD

**Issue by b1gr3db** [AFLplusplus/AFLplusplus#732]
I'm working on a binary with no source, using preload to input data and using afl-qemu. The program validates the command line when started, so I didn't use @@ in the command line, but instead used an environment variable to point to .cur_input and that worked fine (although not the most elegant solution). 

I'm now trying to use afl-cmin, and attempted to use -f to set the name. It copies the first test case to that file. However, it appears that the name is never provided to afl-showmap so it writes all the test cases to afl-showmap-temp-<pid> rather than using the provided name, with the dynamic pid meaning I can't just hardcode the name either.

**Comment by vanhauser-thc** [comment]
@hexcoder- it is your baby :) if you have the time to look into this.

**Comment by hexcoder-** [comment]
ok, I will have a look.

**Comment by hexcoder-** [comment]
If you set your environment variable to `<outdir>/.traces/.cur_input` (with `<outdir>` being the directory given for `-o`) during the run of afl-cmin it should work, since this is the location where `afl-cmin` is placing the file with input data. `-f` should not be necessary, because you did not use that for fuzzing either (if I understood correctly, you did not give the command lines used...).

**Comment by vanhauser-thc** [comment]
@hexcoder- which environment variable are you talking about?
and if the `-f`option is missing then it should be supported as otherwise afl-cmin cant be used for a target that requires it.

**Comment by hexcoder-** [comment]
@vanhauser-thc: This setup is a bit more complicated from what I get. I am talking about the env var the OP has mentioned (nothing to do with AFL++, i assume).

During fuzzing:
OP used his OWN environment var to point to the input file for the target. Only the target knows this env var.
OP did not use `@@` (so stdin mode was being used but probably ignored by the target, so I concluded `-f` was not given).
@b1gr3db : Please give your exact commandline used for fuzzing to relieve us from guessing...

So, for afl-cmin, this user supplied env var should now be set to a new location (see above comment), in order to use the right `.cur_input` file there. When fuzzing did not use `-f`, running afl-cmin should not use it neither.

That is all i meant. If this will not help, i need more precise info in order to help.

**Comment by vanhauser-thc** [comment]
I am not about what his special setup is, rather that -f is not supported :) afl-fuzz, afl-cmin.bash etc. all have the option.

**Comment by vanhauser-thc** [comment]
it is about adding the -f option. not special help support. (he wrote about this on the discord and we told him to create an issue)

**Comment by hexcoder-** [comment]
So you mean I can (and should) ignore what the OP wrote here, and focus on `-f`. Well then weird, but ok.

**Comment by hexcoder-** [comment]
@b1gr3db : please check current dev branch, it should be fixed now.

**Comment by b1gr3db** [comment]
Thank-you!
