### ISSUE TITLE
Compiling in chroot env on Android (termux) 

### ISSUE THREAD

**Issue by ghost** [AFLplusplus/AFLplusplus#908]
Trying to compile AFL++ in chroot environment with clang12 (in termux) on Android. However, the linker could not find -lc, whatever library this is. Could not figure it out.

```
ld: cannot find -lc
clang-12: error: linker command failed with exit code 1
```

Any ideas what it could be looking for and how to fix it?

Thanks,

**Comment by marcinguy** [comment]
Tried also build AFL++ binary from AOSP,  but the built binary seg faults. Anybody can help or share AFL++ binary for Android x86_64? Any source to get them?

**Comment by marcinguy** [comment]
Also want it to use it with fpicker https://github.com/ttdennis/fpicker and emulate shared memory via https://github.com/termux/libandroid-shmem.... Since as I understood fpicker needs to access it and on Android it is not available (ashmem is used). Will see if this works. Hence the best if I compile it on termux (aosp binary could have it disabled).

**Comment by ghost** [comment]
Compiled using NDK toolchain. Seems to work.
